-- MySQL Script generated by MySQL Workbench
-- Wed Jun 10 09:40:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema basereservas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basereservas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basereservas` DEFAULT CHARACTER SET utf8 ;
USE `basereservas` ;

-- -----------------------------------------------------
-- Table `basereservas`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereservas`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NULL,
  `aPaterno` VARCHAR(20) NULL,
  `aMaterno` VARCHAR(20) NULL,
  `tipoDoc` VARCHAR(20) NULL,
  `numDoc` VARCHAR(8) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereservas`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereservas`.`Trabajador` (
  `idTrabajador` INT NOT NULL,
  `sueldo` DECIMAL(7,2) NOT NULL,
  `acceso` VARCHAR(20) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idTrabajador`),
  CONSTRAINT `fk_persona_trabajador`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `basereservas`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereservas`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereservas`.`Cliente` (
  `idCliente` INT NOT NULL,
  `codCliente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `basereservas`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereservas`.`Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereservas`.`Habitacion` (
  `idHabitacion` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(4) NOT NULL,
  `piso` VARCHAR(2) NOT NULL,
  `descripcion` VARCHAR(512) NULL,
  `caracteristicas` VARCHAR(512) NULL,
  `precioDiario` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `tipoHabitacion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idHabitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereservas`.`Rereserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereservas`.`Rereserva` (
  `idRereserva` INT NOT NULL,
  `idHabitacion` INT NOT NULL,
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `idTrabajador` INT NOT NULL,
  `tipoReserva` VARCHAR(30) NOT NULL,
  `fechaReserva` DATE NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `fechaSalida` DATE NOT NULL,
  `costoAlojamiento` DECIMAL(7,2) NOT NULL,
  `observacion` VARCHAR(512) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idRereserva`),
  INDEX `fk_reserva_cliente_idx` (`idCliente` ASC),
  INDEX `fk_reserva_habitacion_idx` (`idHabitacion` ASC),
  INDEX `fk_reserva_trabajador_idx` (`idTrabajador` ASC),
  CONSTRAINT `fk_reserva_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `basereservas`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_habitacion`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `basereservas`.`Habitacion` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_trabajador`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `basereservas`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereservas`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereservas`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `idReserva` INT NOT NULL,
  `tipoComprobante` VARCHAR(20) NOT NULL,
  `numComprobante` VARCHAR(12) NOT NULL,
  `igv` DECIMAL(4,2) NOT NULL,
  `totalPago` DECIMAL(9,2) NOT NULL,
  `fechaEmision` DATE NOT NULL,
  `fechaPago` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_pago_reserva_idx` (`idReserva` ASC),
  CONSTRAINT `fk_pago_reserva`
    FOREIGN KEY (`idReserva`)
    REFERENCES `basereservas`.`Rereserva` (`idRereserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereservas`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereservas`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descipcion` VARCHAR(255) NULL,
  `unidadMedida` VARCHAR(20) NOT NULL,
  `precioVenta` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereservas`.`Consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereservas`.`Consumo` (
  `idConsumo` INT NOT NULL,
  `idReserva` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` DECIMAL(7,2) NOT NULL,
  `precioVenta` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idConsumo`),
  INDEX `fk_consumo_reserva_idx` (`idReserva` ASC),
  INDEX `fk_consumo_producto_idx` (`idProducto` ASC),
  CONSTRAINT `fk_consumo_reserva`
    FOREIGN KEY (`idReserva`)
    REFERENCES `basereservas`.`Rereserva` (`idRereserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `basereservas`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
